version: '3'

services:

  back-end:
    build:
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3030:3030"
    command: npm run start

  front-end:
    build:
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "5173:5173"
    command: npm run dev
